# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/uart_UART_0_0.xci
# IP: The module: 'uart_UART_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_fifo_fifo_generator_0_0 || ORIG_REF_NAME==uart_fifo_fifo_generator_0_0}]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_fifo_fifo_generator_0_0 || ORIG_REF_NAME==uart_fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/constrs_1/imports/fpgaprojects/Basys3_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_UART_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/uart_fifo_ooc.xdc

# IP: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/uart_UART_0_0.xci
# IP: The module: 'uart_UART_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_fifo_fifo_generator_0_0 || ORIG_REF_NAME==uart_fifo_fifo_generator_0_0}]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/ip/uart_fifo_fifo_generator_0_0/uart_fifo_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_fifo_fifo_generator_0_0 || ORIG_REF_NAME==uart_fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/constrs_1/imports/fpgaprojects/Basys3_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_UART_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/tim/fpgaprojects/factorise2/factorise2.srcs/sources_1/bd/uart/ip/uart_UART_0_0/sources_1/bd/uart_fifo/uart_fifo_ooc.xdc
