# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpgaprojects/Basys3_Master.xdc

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart}]

# IP: bd/uart/ip/uart_UART_0_0/uart_UART_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_UART_0_0 || ORIG_REF_NAME==uart_UART_0_0}]

# Block Designs: bd/dataentry_ram/dataentry_ram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dataentry_ram || ORIG_REF_NAME==dataentry_ram}]

# IP: bd/dataentry_ram/ip/dataentry_ram_blk_mem_gen_0_0/dataentry_ram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dataentry_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==dataentry_ram_blk_mem_gen_0_0}]

# Block Designs: bd/stringsrom/stringsrom.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stringsrom || ORIG_REF_NAME==stringsrom}]

# IP: bd/stringsrom/ip/stringsrom_blk_mem_gen_0_0/stringsrom_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stringsrom_blk_mem_gen_0_0 || ORIG_REF_NAME==stringsrom_blk_mem_gen_0_0}]

# XDC: bd/uart/uart_ooc.xdc

# XDC: bd/dataentry_ram/dataentry_ram_ooc.xdc

# XDC: bd/stringsrom/stringsrom_ooc.xdc
